gitops:
  # Need to add ssh-key to do ssh
  # repo: 'git@github.com:joosthb/k3s-cluster'
  repo: https://github.com/joosthb/k3s-cluster
  revision: main

# List of application corresponding to different sync waves
apps:
    # argo-cd
  - name: argo-cd
    namespace: default
    path: system/argo-cd
    syncWave: 0
    # root app of apps
  - name: root
    namespace: default
    path: system/root
    syncWave: 1
    # whoami app
  - name: cert-manager
    namespace: default
    path: system/cert-manager
    syncWave: 1
    # whoami app
  - name: whoami
    namespace: default
    path: applications/whoami
    syncWave: 1
    # k8s dashboard
  - name: dashboard
    namespace: kubernetes-dashboard
    path: system/dashboard
    syncWave: 1