apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@hendricksen.net
    privateKeySecretRef:
      name: letsencrypt-prod
    
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
      # - dns01:
      #     cloudflare:
      #       email: cloudflare@hendricksen.net
      #       apiTokenSecretRef:
      #         name: cloudflare-api-token-secret
      #         key: api-token
      #   selector:
      #     dnsZones:
      #     - 'home.lednakirf.nl'
      #     - '*.home.lednakirf.nl'