apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
spec:
  rules:
    - host: whoami.home.lednakirf.nl
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: whoami-service
                port:
                  number: 80