apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: whoami
#  namespace: default
 annotations:
   cert-manager.io/issuer: "letsencrypt-prod"
spec:
 tls:
   - hosts:
       - whoami.example.com
     secretName: tls-whoami-ingress-dns
 rules:
   - host: whoami.home.lednakirf.nl
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: whoami
               port:
                 name: web